openxlsx: add missing includes
OpenXLSX/headers/XLCellReference.hpp:65:37: error: ‘uint32_t’ was not declared in this scope
OpenXLSX/headers/XLColor.hpp:166:9: error: ‘uint8_t’ does not name a type