emsdk: tar is required
Unpacking '/home/user/.conan2/p/b/emsdk370f30dc7fb1c/b/src/downloads/b363a836e75a245c548b7a6a021822d8c9e4c6df-wasm-binaries.tar.xz' to '/home/user/.conan2/p/b/emsdk370f30dc7fb1c/b/src/upstream'
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
['tar', '-xf', '/home/user/.conan2/p/b/emsdk370f30dc7fb1c/b/src/downloads/b363a836e75a245c548b7a6a021822d8c9e4c6df-wasm-binaries.tar.xz', '--strip', '1'] failed with error code 2!
error: installation failed!